environment=stage

deviceName=Vivo V25

appPackage=com.titan.eyecare
appActivity=com.titan.eyecare.ui.launcher.SplashScreen

searchProduct=GM344PK1F

isLoginRequired=false
mobileNumber=8698294937
appiumURL=http://127.0.0.1:4723
appName=TEP_STAGE.apk
apkPath=D:\\Apps\\TEP_STAGE.apk
platformName=Android
