browserstack.username=pareshpatil_0ktlGj
browserstack.accessKey=qt57HZ6sFMP6cpGKFdDR

browserstack.app=bs://d02dbf4aca536bf7e861721a1060ee8b27a123e7

browserstack.device=Samsung Galaxy S24
browserstack.osVersion=14.0

browserstack.project=Titan Mobile Automation
browserstack.build=Regression
browserstack.session=Purchase Journey