browserstack.username=qualityanalyst_WV8fB9
browserstack.accessKey=mb4TzJuDie8KpeaCDqVC

browserstack.app=bs://bc1628b54fc74d82e5ef7d7e1ae2f0ddd3d95e06

browserstack.device=Samsung Galaxy S24
browserstack.osVersion=14.0

browserstack.project=Titan Mobile Automation
browserstack.build=Regression
browserstack.session=Purchase Journey