browserstack.username=qualityanalyst_WV8fB9
browserstack.accessKey=mb4TzJuDie8KpeaCDqVC

browserstack.app=bs://cf3e51cff02bb58335afa1809b04f25c3e28d1c6

browserstack.device=Samsung Galaxy S24
browserstack.osVersion=14.0

browserstack.project=Titan Eyewear Mobile Automation
browserstack.build=Regression
browserstack.session=Purchase Journey