name: Titan Automation

on:
  push:
    branches:
      - main
  schedule:
    # GitHub cron is always UTC: 08:00 UTC = 01:30 PM IST
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        env:
          EXECUTION_MODE: browserstack
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          TEST_DEFAULT_USER_MOBILE: ${{ secrets.TEST_DEFAULT_USER_MOBILE }}
          TEST_DEFAULT_USER_PASSWORD: ${{ secrets.TEST_DEFAULT_USER_PASSWORD }}
        run: mvn clean test -DsuiteXmlFile=testng-parallel-purchase-rows.xml
